apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: codegen2bms-sep30-1 
  janus-idp.io/tekton: codegen2bms-sep30-1
  backstage.io/kubernetes-id: codegen2bms-sep30-1
  backstage.io/kubernetes-namespace: codegen2bms-sep30-1 
  app.kubernetes.io/part-of: codegen2bms-sep30-1
resources: 
- application-dev.yaml